(() => {
'use strict';
const RAW='https://raw.githubusercontent.com/Junior162009/MindMathArcade/main/';
const API='https://api.github.com/repos/Junior162009/MindMathArcade/contents/';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'');
async function json(url,fallback){try{const r=await fetch(url,{cache:'no-store'});return r.ok?await r.json():fallback}catch{return fallback}}
async function loadImages(){const files=await json(API+'img',[]);return Array.isArray(files)?files.filter(f=>/\.(png|jpe?g|webp)$/i.test(f.name)).map(f=>({...f,key:slug(f.name.replace(/\.[^.]+$/,''))})):[]}
function findImage(game,images){if(game.imageUrl)return /^https?:/i.test(game.imageUrl)?game.imageUrl:RAW+game.imageUrl.replace(/^\//,'');const key=slug(game.name);let hit=images.find(x=>x.key===key)||images.find(x=>key.includes(x.key)||x.key.includes(key));if(!hit){const aliases={atrapaelnumer:'atrapa',mathbattlebeta:'mathbattle',mathbattle:'mathbattle',cookieclicker:'cookie',reinoPixelado:'reino',banderquiz:'banderquiz',ecorecolector:'ecorecolector',animalandia:'animalandia',bitrush:'bitrush'};const a=aliases[key];if(a)hit=images.find(x=>x.key.includes(a))}return hit?.download_url||''}
async function loadGames(){const games=await json(RAW+'data/games.json',[]);const images=await loadImages();return (Array.isArray(games)?games:[]).map(g=>({...g,image:findImage(g,images)}))}
function render(games){const grid=document.querySelector('.game-grid');if(!grid)return;if(!games.length){grid.innerHTML='<p>No se encontraron juegos publicados.</p>';return}grid.innerHTML=games.map((g,i)=>{const img=g.image?`<img src="${esc(g.image)}" alt="${esc(g.name)}" loading="lazy">`:`<span class="game-art">${esc(g.icon||'🎮')}</span>`;return `<article class="game-card tm-live-game-card"><div class="game-image">${img}<span class="game-badge">${esc(g.category||'Juego')}</span></div><div class="game-info"><h3>${esc(g.name)}</h3><p>${esc(g.desc||g.description||'Juego de TecnoMath')}</p><div class="game-meta"><small>🎮 ${esc(g.deviceCompatibility||'Web')}</small><button class="tm-btn tm-btn-primary" data-route="${esc(g.url||'')}">Jugar</button></div></div></article>`}).join('');grid.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{const p=b.dataset.route;if(p)location.assign(new URL(p,'https://tecnomath.online/').href)});}
function styles(){if(document.getElementById('tm-games-original-art'))return;const s=document.createElement('style');s.id='tm-games-original-art';s.textContent='.tm-live-game-card{overflow:hidden}.tm-live-game-card .game-image{position:relative;min-height:180px;background:var(--tm-surface-2);overflow:hidden}.tm-live-game-card .game-image img{width:100%;height:100%;min-height:180px;object-fit:cover;display:block}.tm-live-game-card .game-badge{position:absolute;top:12px;left:12px;z-index:2}.tm-live-game-card .game-art{display:grid;place-items:center;height:180px;font-size:4rem}';document.head.appendChild(s)}
async function init(){styles();render(await loadGames())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();