(() => {
'use strict';
const OWNER='Junior162009', REPO='MindMathArcade', BRANCH='main';
const RAW=`https://raw.githubusercontent.com/${OWNER}/${REPO}/${BRANCH}/`;
const API=`https://api.github.com/repos/${OWNER}/${REPO}`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'');
async function json(url,fallback){try{const r=await fetch(url,{cache:'no-store'});return r.ok?await r.json():fallback}catch{return fallback}}
function imageScore(path,name,gamePath){const p=norm(path),n=norm(name),base=norm(gamePath.split('/').slice(-2,-1)[0]);let s=0;if(p.includes('/'+base+'/'))s+=80;if(p.includes('cover'))s+=50;if(p.includes('thumbnail'))s+=45;if(p.includes('banner'))s+=35;if(p.includes('logo'))s+=30;if(p.includes('icon'))s+=25;if(p.includes(n))s+=25;if(p.endsWith('.png'))s+=5;return s}
function parseIndexImages(html,gamePath){const found=[];const re=/<(?:img|source)[^>]+(?:src|srcset)=["']([^"']+)["'][^>]*>|<(?:meta)[^>]+(?:property|name)=["'](?:og:image|twitter:image)["'][^>]+content=["']([^"']+)["']/gi;let m;while((m=re.exec(html))){const raw=m[1]||m[2];if(!raw||raw.startsWith('data:'))continue;try{const u=new URL(raw,RAW+gamePath);if(/\.(png|jpe?g|webp|gif|svg)(\?|$)/i.test(u.pathname))found.push(u.href)}catch{}}return [...new Set(found)]}
async function buildTree(){const r=await json(`${API}/git/trees/${BRANCH}?recursive=1`,null);return r?.tree||[]}
async function discoverGames(){const tree=await buildTree();const indexes=tree.filter(x=>x.type==='blob'&&/^games\/[^/]+\/index\.html$/i.test(x.path));const published=await json(RAW+'games/published-games.json',[]);const catalog=await json(RAW+'data/games.json',[]);const byUrl=new Map();[...(Array.isArray(catalog)?catalog:[]),...(Array.isArray(published)?published:[])].forEach(g=>{if(g?.url)byUrl.set(g.url,g)});const games=[];for(const idx of indexes){const path=idx.path;const meta=byUrl.get(path)||{};const folder=path.split('/')[1];let name=meta.name||folder.replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());let html=await json(RAW+path,'');if(html){const title=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/<[^>]+>/g,'').trim();if(title&&!meta.name)name=title.replace(/^\p{Extended_Pictographic}\s*/u,'').trim()}const candidates=tree.filter(x=>x.type==='blob'&&/^games\/[^/]+\//i.test(x.path)&&x.path.startsWith(`games/${folder}/`)&&/\.(png|jpe?g|webp|gif|svg)$/i.test(x.path));const htmlImages=parseIndexImages(html,path);const explicit=meta.imageUrl?new URL(meta.imageUrl,RAW).href:'';let image=explicit||htmlImages[0]||'';if(!image&&candidates.length){candidates.sort((a,b)=>imageScore(b.path,name,path)-imageScore(a.path,name,path));image=RAW+candidates[0].path}games.push({...meta,name,url:path,image,icon:meta.icon||'🎮'})}const seen=new Set();return games.filter(g=>{if(seen.has(g.url))return false;seen.add(g.url);return true})}
function render(games){const grid=document.querySelector('.game-grid');if(!grid)return;if(!games.length){grid.innerHTML='<p class="tm-muted">No se encontraron juegos.</p>';return}grid.innerHTML=games.map(g=>{const art=g.image?`<img src="${esc(g.image)}" alt="${esc(g.name)}" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="game-art" hidden>${esc(g.icon||'🎮')}</span>`:`<span class="game-art">${esc(g.icon||'🎮')}</span>`;return `<article class="game-card tm-live-game-card"><div class="game-image">${art}<span class="game-badge">${esc(g.category||'Juego')}</span></div><div class="game-info"><h3>${esc(g.name)}</h3><p>${esc(g.desc||g.description||'Juego educativo de TecnoMath')}</p><div class="game-meta"><small>🎮 ${esc(g.deviceCompatibility||'Web')}</small><button class="tm-btn tm-btn-primary" type="button" data-route="${esc(g.url)}">Jugar</button></div></div></article>`}).join('');grid.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>location.assign(new URL(b.dataset.route,'https://tecnomath.online/').href)))}
function styles(){if(document.getElementById('tm-games-original-art'))return;const s=document.createElement('style');s.id='tm-games-original-art';s.textContent='.tm-live-game-card{overflow:hidden}.tm-live-game-card .game-image{position:relative;min-height:190px;background:var(--tm-surface-2);overflow:hidden}.tm-live-game-card .game-image img{width:100%;height:190px;object-fit:cover;display:block}.tm-live-game-card .game-badge{position:absolute;top:12px;left:12px;z-index:3}.tm-live-game-card .game-art{display:grid;place-items:center;height:190px;font-size:4rem}';document.head.appendChild(s)}
async function init(){styles();const games=await discoverGames();render(games);window.TecnoMathGames=games}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();